ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.capability
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.cel
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.common
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.configcache
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.configurations
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.core.genericinterfaceparameters
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.customermanagement
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.dataaccess
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.dynamicfunction
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.event
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.globalconfig
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.integration
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.integrationtest
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.invoiceaggregation
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.invoiceaggregation.customerbillingcycle
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.oam
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.periodicaction
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.productiondependencies
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.productselection
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.productstatus
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.race
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.reasoncode
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.refill
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.rf.core
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.runtimeflow
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.servicedetermination
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.serviceprovider
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.services
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.session
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.transport
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.vre
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.bucketmanagement
ssh://gerrit.epk.ericsson.se:29418/charging/com.ericsson.bss.rm.charging.prioritization